apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-environments
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - environment: dev
        namespace: shop-dev
      - environment: staging
        namespace: shop-staging
      - environment: prod
        namespace: shop-prod
  
  template:
    metadata:
      name: 'shop-{{environment}}'
      labels:
        environment: '{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/GoogleCloudPlatform/microservices-demo.git
        targetRevision: HEAD
        path: helm-chart
        helm:
          values: |
            networkPolicies:
              create: false
            sidecars:
              create: false
            frontend:
              externalService: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
